name: TNT-Tensor4Transportation
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - networkx
  - numpy
  - pandas
  - matplotlib
  - zarr
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - tensorly
    - Pyomo
#conda env create -f environment.yml
#conda activate your_environment_name